added BarCrawlPage
porapobaram/ppb_frontend pull request #3
Opened 2020-01-27 23:25 UTC by NataliyaPetruk

2020-01-28 11:26 UTC, andrewkryshtal commented on src/ui/components/BarCrawlPage/BarCrawlPageContainer.js
> +          return <BarCrawlPageComponent key={uid(item)} item={item} />;
в `key` необязательно запихивать uid, давай я буду писать айдишку в саму схему данных и по ней будем делать выборку. сделай пока 

```
const test =  {
	bcId: "random number, ill do it on backend",
	bcImg:
		"https://gdb.rferl.org/059EC58A-9005-4B73-AAAB-BABDC1DA67B7_cx0_cy6_cw0_w408_r1.jpg",
	bcName: "BAR CRAWL 1",
	bcTime: "20:00 - 2:00",
	bcPrice: "300 грн",
	bcDescription:
		"«Укрзалізниця» потребує 51,2 мільярда гривень протягом шести років на оновлення локомотивного парку, повідомив член правління компанії Франтішек Буреш"
},
```

2020-01-28 11:26 UTC, andrewkryshtal commented on src/ui/components/BarCrawlPage/BarCrawlPageContainer.js
> +          return <BarCrawlPageComponent key={uid(item)} item={item} />;
так мы просто уберем использование лишней библиотеки, и это только в плюс

2020-01-28 11:28 UTC, andrewkryshtal commented on src/ui/components/BarCrawlPage/BarCrawlPageContainer.js
> +      <Slider {...settings}>
перенеси слайдер в компонент и прокинь все настройки с контейнера. Контейнер должен вернуть компонент, в котором уже будет слайдер

2020-01-28 11:36 UTC, andrewkryshtal commented on src/ui/components/BarCrawlPage/index.js
> +export default BarCrawlPageContainer;
так, внимательно:

компонент пейджи является оберткой, где лежат уже баркроулы. Пейджа принимает компонент баркроула, так что нужен еще один компонент

должен возвращаться компонент, куда ты уже прокидываешь данные и который мапишь на пейдже

```<BarCrawlItem {*all props from page component*} />```

2020-01-28 11:42 UTC, andrewkryshtal requested changes
сделать дополнительный компонент BarCrawlItem, и сделать его функциональным

2020-01-29 21:16 UTC, andrewkryshtal submitted a review, later dismissed
умница! 🏅

2020-01-29 21:48 UTC, andrewkryshtal commented on src/index.js
>  import ReactDOM from "react-dom";
так, давай в js файлах в импортах использовать одинарные кавычки. Будем попутно договариваться про кодстайл

2020-01-30 19:16 UTC, LiudmylaKostenko submitted a review, later dismissed

2020-01-30 19:40 UTC, LiudmylaKostenko approved these changes

2020-02-01 22:30 UTC, andrewkryshtal commented on public/index.html
> +  <link rel="stylesheet" type="text/css" charset="UTF-8"
TODO: все таки отсюда надо будет поубирать стили, совсем не годится

2020-02-01 22:31 UTC, andrewkryshtal approved these changes

2020-02-01 22:32 UTC, merged