Team 2 kuzmin
porapobaram/ppb_frontend pull request #4
Opened 2020-01-28 12:14 UTC by N-icko

Вёрстка + немного функционала.

2020-01-29 21:18 UTC, andrewkryshtal commented on src/index.js
> +import ButtonContainer from "./ui/components/ButtonPage/Button";
переименуй компонент в RandomizeScreen, так будет понятнее на фоне всех компонентов что это такое

2020-01-29 21:21 UTC, andrewkryshtal commented on src/ui/components/ButtonPage/Button/ButtonComponent.js
> +  const clickFunc = () => {
это нужно положить в контейнер, если ты сделал функциональный юай компонент - то тут по сути в него уже должно все заходить из контейнера

2020-01-29 21:22 UTC, andrewkryshtal commented on src/ui/components/LoginPage/LoginPageContainer.js
> -import React, { Component } from 'react';
зачем это тут? наверное это надо удалить. И удали map css файлы, у тебя скорее всего включился на них вотчер в вскоде

2020-01-29 21:23 UTC, andrewkryshtal commented on src/ui/components/LoginPage/LoginPageContainer.js
> -import React, { Component } from 'react';
да, удалить все что связано с LoginPageComponent итд

2020-01-29 21:23 UTC, andrewkryshtal requested changes
немножечко правок

2020-01-29 21:49 UTC, andrewkryshtal commented on src/index.js
> +import ButtonContainer from "./ui/components/ButtonPage/Button";
так, давай в js файлах в импортах использовать одинарные кавычки. Будем попутно договариваться про кодстайл

2020-01-30 15:43 UTC, andrewkryshtal commented on src/ui/components/RandomizeScreen/index.js
> +import './RandomizeScreenComponent.scss';
стили импортятся в файл компонента, а не в index.js

2020-01-30 15:43 UTC, andrewkryshtal requested changes
дополнительный комментарий

2020-01-30 19:24 UTC, LiudmylaKostenko submitted a review, later dismissed

2020-02-06 14:25 UTC, andrewkryshtal approved these changes
🏅

2020-02-06 14:26 UTC, merged